[package]
name = "vm_m6"
version = "0.1.0"
edition = "2018"
authors = []
homepage = "https://www.zkamoeba.com/"
repository = "https://github.com/ZKAmoeba-Micro/micro-2"
license = "Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]

[dependencies]
zkevm-assembly = { git = "https://github.com/ZKAmoeba-Micro/micro-zkEVM-assembly.git", tag = "v1.3.1-rc0" }
micro_crypto = { path = "../../lib/crypto" }
micro_types = { path = "../../lib/types" }
micro_utils = { path = "../../lib/utils" }
micro_config = { path = "../../lib/config" }
micro_state = { path = "../../lib/state" }
micro_storage = { path = "../../lib/storage" }

zk_evm = { git = "https://github.com/ZKAmoeba-Micro/micro-zk_evm.git", tag = "v1.3.1-rc0" }
micro_contracts = { path = "../../lib/contracts" }

hex = "0.4"
thiserror = "1.0"
itertools = "0.10"
once_cell = "1.7"
vlog = { path = "../../lib/vlog" }

tracing = "0.1"

[dev-dependencies]
tempfile = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
