version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    environment:
      - PLUGIN_CONFIG

  zk:
    image: "matterlabs/zk-environment:latest2.0"
    depends_on:
      - geth
      - postgres
    security_opt:
      - seccomp:unconfined
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/micro
      - /usr/src/cache:/usr/src/cache
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/src/keys:/mnt/prover_setup_keys
    environment:
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
      - SCCACHE_GCS_OAUTH_URL=http://169.254.169.254/computeMetadata/v1/instance/service-accounts/gha-ci-runners@zkamoeba-infra.iam.gserviceaccount.com/token
      - SCCACHE_ERROR_LOG=/tmp/sccache_log.txt
      - SCCACHE_GCS_RW_MODE=READ_WRITE
      - CI=1
      - GITHUB_WORKSPACE=$GITHUB_WORKSPACE
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
