version: '3.2'
services:
  lotus:
    image: "zkamoeba/lotus:latest"
    ports:
      - "1234:1234"
    volumes:
      - type: bind
        source: ./volumes/lotus
        target: /var/lib/lotus/data
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
