# Note: this file doesn't depend on `base` env and will not contain variables from there.
# All the variables must be provided explicitly.
# This is on purpose: if EN will accidentally depend on the main node env, it may cause problems.

test_database_url = "postgres://postgres@localhost/micro_local_test_ext_node"
database_url = "postgres://postgres@localhost/micro_local_ext_node"
database_pool_size = 50
micro_action = "dont_ask"

[en]
http_port = 3060
ws_port = 3061
prometheus_port = 3322
healthcheck_port = 3081
threads_per_server = 128
l2_chain_id = 270
l1_chain_id = 31415926

req_entities_limit = 10000

state_cache_path = "./db/ext-node/state_keeper"
merkle_tree_path = "./db/ext-node/lightweight"
max_l1_batches_per_tree_iter = 20

main_node_url = "http://127.0.0.1:3050"
eth_client_url = "http://127.0.0.1:1234/rpc/v1"

api_namespaces = ["eth", "web3", "net", "pubsub", "zks", "en", "debug"]

# Note:
# `bootloader_hash` and `default_aa_hash` are overridden from the `.init.env` values by `zk` tool.
bootloader_hash = "0x0100091ba79ef3787d87bc4d54a646390bf52aa3fa0cc4e8bec039323e3f7030"
default_aa_hash = "0x0100065dc386f7b648718f2a0b08887b8d813e6b6728936fecb16a4bef7d5fd5"

# Whether to try using MultiVM
# WARN: Only to be used locally until the feature is fully tested.
experimental_multivm_support = false

with_prover = false

[rust]
# `RUST_LOG` environmnet variable for `env_logger`
# Here we use TOML multiline strings: newlines will be trimmed.
log = """\
warn,\
micro_core=debug,\
micro_dal=info,\
micro_eth_client=info,\
micro_storage=info,\
micro_merkle_tree=info,\
micro_state=debug,\
micro_utils=debug,\
micro_types=info,\
loadnext=info,\
vm=info,\
micro_external_node=info,\
cross_nodes_checker=debug,\
"""

# `RUST_BACKTRACE` variable
backtrace = "full"
lib_backtrace = "1"
