[package]
name = "rocksdb_util"
version = "0.1.0"
edition = "2021"
authors = []
homepage = "https://www.zkamoeba.com/"
repository = "https://github.com/ZKAmoeba-Micro/micro-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
micro_config = { path = "../../lib/config" }
micro_storage = { path = "../../lib/storage" }

anyhow = "1.0"
clap = { version = "4.2.4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0.2"
