[package]
name = "verified_sources_fetcher"
version = "0.1.0"
edition = "2021"
authors = []
homepage = "https://www.zkamoeba.com/"
repository = "https://github.com/ZKAmoeba-Micro/micro"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
micro_dal = { path = "../../lib/dal" }
micro_types = { path = "../../lib/types" }
micro_config = { path = "../../lib/config" }
micro_env_config = { path = "../../lib/env_config" }

anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
