[package]
name = "micro_circuit_synthesizer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "micro_circuit_synthesizer"
path = "src/main.rs"

[dependencies]
micro_dal = { path = "../../lib/dal", version = "1.0" }
micro_queued_job_processor = { path = "../../lib/queued_job_processor", version = "1.0" }
micro_config = { path = "../../lib/config", version = "1.0" }
micro_object_store = { path = "../../lib/object_store", version = "1.0" }
micro_types = { path = "../../lib/types", version = "1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }
prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
micro_prover_utils = {path = "../../lib/prover_utils", version = "1.0" }

zkevm_test_harness = { git = "https://github.com/ZKAmoeba-Micro/micro-zkevm_test_harness.git", branch = "main"}
prover-service = { git = "https://github.com/ZKAmoeba-Micro/micro-heavy-ops-service.git", branch = "main", features=["legacy"], default-features=false}

structopt = "0.3.26"
tokio = { version = "1.23.0", features = ["full"] }
futures = { version = "0.3", features = ["compat"] }
ctrlc = { version = "3.1", features = ["termination"] }
local-ip-address = "0.5.0"
metrics = "0.20"
