# micro chain parameters

[chain.eth]
# Name of the used Ethereum network
network = "localhost"
# Name of current micro network
# Used for Sentry environment
micro_network = "localhost"
# ID of current micro network treated as ETH network ID.
# Used to distinguish micro from other Web3-capable networks.
micro_network_id = 380

[chain.state_keeper]
fee_account_addr = "0x26937d59db4463254c930D5f31353F14AA89a0F7"

# Detones the amount of slots for transactions in the block.
transaction_slots = 1024

max_allowed_l2_tx_gas_limit = 4000000000
block_commit_deadline_ms = 180000
miniblock_commit_deadline_ms = 1000
# Max gas that can used to include single block in aggregated operation
max_single_tx_gas = 12000000

# Configuration option for block to be sealed in case
# it takes more percentage of the max block capacity than this value.
close_block_at_geometry_percentage = 0.95
# Configuration option for block to be sealed in case
# it takes more percentage of the max block capacity than this value.
close_block_at_eth_params_percentage = 0.95

# Configuration option for block to be sealed in case
# it takes more percentage of the max block capacity than this value.
close_block_at_gas_percentage = 0.95

# Configuration option for tx to be rejected in case
# it takes more percentage of the block capacity than this value.
reject_tx_at_geometry_percentage = 0.95
# Configuration option for block to be sealed in case
# it takes more percentage of the max block capacity than this value.
reject_tx_at_eth_params_percentage = 0.95

# Configuration option for block to be sealed in case
# it takes more percentage of the max block gas capacity than this value.
reject_tx_at_gas_percentage = 0.95

bootloader_hash = "0x0100038581be3d0e201b3cc45d151ef5cc59eb3a0f146ad44f0f72abf00b594c"
default_aa_hash = "0x0100038dc66b69be75ec31653c64cb931678299b9b659472772b2550b703f41c"

# The price the operator spends on 1 gas of computation in wei.
fair_l2_gas_price = 250000000
#The heartbeat path of L2 layer nodes.
l2_node_heart_beat_url = "0.0.0.0:3052"
# Max number of computational gas that validation step is allowed to take.
validation_computational_gas_limit = 600000
save_call_traces = true

[chain.operations_manager]
# Sleep time when there is no new input data
delay_interval = 100

[chain.mempool]
sync_interval_ms = 10
sync_batch_size = 1000
capacity = 10_000_000
stuck_tx_timeout = 86400 # 1 day in seconds
remove_stuck_txs = true

[chain.circuit_breaker]
sync_interval_ms = 180000
http_req_max_retry_number = 5
http_req_retry_interval_sec = 2
