[proof_data_handler]
http_port=3320
proof_generation_timeout_in_secs=18000
protocol_version_loading_mode="FromEnvVar"
fri_protocol_version_id=2

# micro assignments parameters
retry_interval_ms=30000
once_score=1

