[package]
name = "micro_server"
version = "0.1.0"
edition = "2021"
authors = []
homepage = "https://www.zkamoeba.com/"
repository = "https://github.com/ZKAmoeba-Micro/micro"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
micro_config = { path = "../../lib/config" }
micro_env_config = { path = "../../lib/env_config" }
micro_storage = { path = "../../lib/storage" }
micro_utils = { path = "../../lib/utils" }
micro_types = { path = "../../lib/types" }
micro_core = { path = "../../lib/micro_core" }
vlog = { path = "../../lib/vlog" }

anyhow = "1.0"
clap = { version = "4.2.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
futures = "0.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
