[package]
name = "setup_key_generator_and_server"
version = "1.0.0"
edition = "2018"
authors = []
homepage = ""
repository = "https://github.com/ZKAmoeba-Micro/micro"
license = "Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]

[lib]
name = "micro_setup_key_server"
path = "src/lib.rs"

[[bin]]
name = "micro_setup_key_generator"
path = "src/main.rs"

[dependencies]
micro_types = {path = "../../lib/types", version = "1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }
micro_config = { path = "../../lib/config", version = "1.0" }

circuit_testing = {git = "https://github.com/ZKAmoeba-Micro/micro-circuit_testing.git", branch = "main"}
api = { git = "https://github.com/ZKAmoeba-Micro/micro-heavy-ops-service.git", branch = "main", features=["gpu"], default-features=false}
prover-service = { git = "https://github.com/ZKAmoeba-Micro/micro-heavy-ops-service.git", branch = "main", features=["gpu"], default-features=false}
zkevm_test_harness = { git = "https://github.com/ZKAmoeba-Micro/micro-zkevm_test_harness.git", branch = "main"}

structopt = "0.3.26"
itertools = "0.10.5"
