[package]
name = "micro_external_node"
version = "0.1.0"
edition = "2021"
authors = []
homepage = "https://www.zkamoeba.com/"
repository = "https://github.com/ZKAmoeba-Micro/micro"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
micro_core = { path = "../../lib/micro_core" }
micro_dal = { path = "../../lib/dal" }
micro_config = { path = "../../lib/config" }
micro_storage = { path = "../../lib/storage" }
micro_utils = { path = "../../lib/utils" }
micro_state = { path = "../../lib/state" }
micro_basic_types = { path = "../../lib/basic_types" }
micro_contracts = { path = "../../lib/contracts" }

prometheus_exporter = { path = "../../lib/prometheus_exporter" }
micro_health_check = { path = "../../lib/health_check" }
micro_web3_decl = { path = "../../lib/web3_decl" }
micro_types = { path = "../../lib/types" }
vlog = { path = "../../lib/vlog" }

anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
envy = "0.4"
url = "2.4"
clap = { version = "4.2.4", features = ["derive"] }
tracing = "0.1"
