[package]
name = "micro_external_node"
version = "1.0.0"
edition = "2018"
authors = []
homepage = ""
repository = "https://github.com/zkamoeba/micro"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "micro"]
categories = ["cryptography"]
publish = false                                  # We don't want to publish our binaries.

[dependencies]
micro_core = { path = "../micro_core", version = "1.0" }
micro_dal = { path = "../../lib/dal", version = "1.0" }
micro_config = { path = "../../lib/config", version = "1.0" }
micro_storage = { path = "../../lib/storage", version = "1.0" }
micro_eth_client = { path = "../../lib/eth_client", version = "1.0" }
micro_basic_types = { path = "../../lib/basic_types", version = "1.0" }
micro_types = { path = "../../lib/types", version = "1.0" }

prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
micro_health_check = { path = "../../lib/health_check", version = "0.1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }

anyhow = "1.0"
tokio = { version = "1", features = ["time"] }
sqlx = "^0.6.0"
sqlx-cli = "^0.6.0"
clap = { version = "3.2.25", features = ["derive"] }
